/*await page.goto('chrome-error://chromewebdata/');
await page.getByRole('button', { name: 'Advanced' }).click();
await page.getByRole('link', { name: 'Proceed to haris-dashboard.' }).click();
await page.goto('https://haris-dashboard.bbil.org/login');
await page.getByRole('textbox', { name: 'Enter your email address' }).click();
await page.getByRole('textbox', { name: 'Enter your email address' }).fill('harismashuk92@gmail.com');
await page.getByRole('button', { name: 'Continue' }).click();
await page.getByRole('textbox', { name: 'Enter your password' }).click();
await page.getByRole('textbox', { name: 'Enter your password' }).fill('Kazi#123');
await page.getByRole('button', { name: 'Login' }).click();
await page.getByRole('link', { name: 'layers Products' }).click();
await page.getByRole('link', { name: 'C Categories' }).click();
await page.getByRole('button', { name: 'add Add Category' }).click();
await page.getByRole('textbox', { name: 'Title *' }).click();
await page.getByRole('textbox', { name: 'Title *' }).fill('Category 1234');
await page.getByRole('textbox').nth(1).click();
await page.getByRole('textbox', { name: 'Description' }).click();
await page.getByRole('textbox', { name: 'Page Title' }).click();
await page.getByRole('textbox', { name: 'Description' }).click();
await page.getByRole('textbox', { name: 'Description' }).fill('');
await page.getByRole('textbox', { name: 'Page Title' }).click();
await page.getByRole('textbox', { name: 'Description' }).click();
await page.locator('body').setInputFiles('multi-tools.jpg');
await page.getByRole('textbox', { name: 'Description' }).click();
await page.getByRole('textbox', { name: 'Description' }).fill('category 1234');
await page.getByRole('button', { name: 'Save' }).click();
await page.getByText('Successfully saved').click();
await page.getByText('backup').click();

*/